name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-test-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Get faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Setup git-semver
        run: GO111MODULE=on go get github.com/mdomke/git-semver/v6@v6.0.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=tag::$(git-semver | tr '+' '.')
      - name: Get Repo Owner
        id: get_repo_owner
        run: >
          echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} |
          tr '[:upper:]' '[:lower:]')
      - name: Debug variables
        run: |
          echo "repo_owner: ${{ steps.get_repo_owner.outputs.repo_owner }}"
          echo "tag: ${{ steps.get_tag.outputs.tag }}"
          echo "repo: ${{ github.repository }}"
          echo "git-describe: $(git describe --tags --always)"
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ steps.get_repo_owner.outputs.repo_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Publish functions
        run: >
          OWNER="${{ steps.get_repo_owner.outputs.repo_owner }}"
          TAG="${{ steps.get_tag.outputs.tag }}"
          faas-cli publish
          --disable-stack-pull
          --build-label org.opencontainers.image.source=https://github.com/${{ github.repository }}
          --platforms linux/amd64,linux/arm64